### ISSUE TITLE
python-pptx not working in python 3.10

### ISSUE THREAD

**Issue by kascodeo** [kascodeo/python-pptx#1]
Hi, python-pptx package is not working as intended in python 3.10. Following are steps to reproduce the error.

```python
python3 --version
python3 -m venv .venv
source .venv/bin/activate
pip install python-pptx
python -c 'from pptx import Presentation'
```
Python 3.10.6
Collecting python-pptx
  Using cached python_pptx-0.6.21-py3-none-any.whl
Collecting XlsxWriter>=0.5.7
  Using cached XlsxWriter-3.1.2-py3-none-any.whl (153 kB)
Collecting Pillow>=3.3.2
  Using cached Pillow-10.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
Collecting lxml>=3.1.0
  Using cached lxml-4.9.3-cp310-cp310-manylinux_2_28_x86_64.whl (7.9 MB)
Installing collected packages: XlsxWriter, Pillow, lxml, python-pptx
Successfully installed Pillow-10.0.0 XlsxWriter-3.1.2 lxml-4.9.3 python-pptx-0.6.21
Traceback (most recent call last):
  File "/home/kas/tests/.venv/lib/python3.10/site-packages/pptx/compat/__init__.py", line 10, in <module>
    Container = collections.abc.Container
AttributeError: module 'collections' has no attribute 'abc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kas/tests/.venv/lib/python3.10/site-packages/pptx/__init__.py", line 14, in <module>
    from pptx.api import Presentation  # noqa
  File "/home/kas/tests/.venv/lib/python3.10/site-packages/pptx/api.py", line 15, in <module>
    from .package import Package
  File "/home/kas/tests/.venv/lib/python3.10/site-packages/pptx/package.py", line 6, in <module>
    from pptx.opc.package import OpcPackage
  File "/home/kas/tests/.venv/lib/python3.10/site-packages/pptx/opc/package.py", line 11, in <module>
    from pptx.compat import is_string, Mapping
  File "/home/kas/tests/.venv/lib/python3.10/site-packages/pptx/compat/__init__.py", line 14, in <module>
    Container = collections.Container
AttributeError: module 'collections' has no attribute 'Container'

**Comment by kascodeo** [comment]
This issue is fixed. [python-pptx-fix](https://pypi.org/project/python-pptx-fix/)
